name: artdex
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  nb_utils: ^6.1.0
  dotted_border: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icon/logo.png
    - assets/images/bgLog.png
    - assets/images/bg2.jpg
    - assets/images/bg3.jpg
    - assets/images/bg4.jpg
    - assets/images/via.jpeg
    - assets/images/upload.png
    - assets/images/profile.png
    - assets/images/crown.png
    - assets/images/card.png
    - assets/images/midtrans.png
    - assets/images/lukisan.png
    - assets/images/login.png
  fonts:
    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins Light Italic
      fonts:
        - asset: assets/fonts/Poppins-LightItalic.ttf
    - family: Poppins Light Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Light Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: Poppins Semi Bold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
  uses-material-design: true

